### ISSUE TITLE
Release for IDE protocol v2 (1.1) breaks syntax highlighting

### ISSUE THREAD

**Issue by risavkarna** [idris-community/idris2-mode#12]
Updating to the latest release seems to have misconfigured syntax highlighting. Here's a before and after image of how code is highlighted on my Emacs. 

![Before Update](https://user-images.githubusercontent.com/1485929/147124004-332ffbed-385c-4d91-b1e4-0c21b552b848.png)

![After Update to latest release](https://user-images.githubusercontent.com/1485929/147124730-de955003-d267-47a3-98cd-381bc9608206.png)

Reverting my `idris2-mode` repo to the previous commit brings back the previous highlighting. Also, other languages e.g. Agda are not affected. So I am a bit doubtful about this being an Emacs' config issue or an issue due to a syntax highlighting package conflict on my end.

**Comment by gallais** [comment]
1. What version of idris are you using?
2. What version of idris2-mode (commit hash) are you using?

**Comment by risavkarna** [comment]
1. Idris 2: version 0.5.1
2. Problem appeared when I git pulled to the latest commit (`0ea481d91ef18da6106e0e282f552d4c407ff017`). Reverting back to the one before that (`b035de54a9ba15f62a006877597cc52bb6dcc334`) seems to resolve it. 

I also noticed that lifting holes to lemmas doesn't work consistently - lemma's type definition does not show up sometimes. But seeing the code diff, it is probably not a regression from these two commits (if it's one at all). Will report back in a separate issue if I can spot it again and/or figure out when this happens.

**Comment by risavkarna** [comment]
Could not replicate on another machine, with clean install of Emacs. Probably just my Emacs config issue. Sorry about that :)

**Comment by gallais** [comment]
It's the expected behaviour: the latest [*release*](https://github.com/idris-community/idris2-mode/releases/tag/1.1) is compatible with older versions of the
protocol but the latest *commit* uses the new one where the offsets have been changed.
