### ISSUE TITLE
The REPL freezes doom emacs 29.0.50

### ISSUE THREAD

**Issue by MonAaraj** [idris-community/idris2-mode#23]
Hello! I set up this repository by adding it as a module to emacs, and then I tried to load a file via `C-c C-l`, which would work great. When the REPL shows up, it looks more or less normal, until I try to type anything in it. At that point, for whatever reason; most of the time.. it simply freezes entirely, with one message right before it saying that the buffer became read-only, right after the character was inputted. I need to use C-g to unfreeze it. After turning on debugging at quit, it seems to scream this traceback:
```
Debugger entered--Lisp error: (quit)
  accept-process-output(#<process Idris2 IDE support> 0.1)
  idris2-eval((:repl-completions "main"))
  idris2-repl-complete()
  completion--capf-wrapper(idris2-repl-complete optimist)
  company--capf-wrapper(idris2-repl-complete optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  apply(company-capf prefix)
  company-call-backend-raw(prefix)
  company--force-sync(company-call-backend-raw (prefix) company-capf)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *idris2-repl*> #<window 48 on *idris2-repl*> 5080 59)
  apply(company-idle-begin (#<buffer *idris2-repl*> #<window 48 on *idris2-repl*> 5080 59))
  timer-event-handler([t 25238 53037 955320 nil company-idle-begin (#<buffer *idris2-repl*> #<window 48 on *idris2-repl*> 5080 59) nil 211000 nil])
```
Thank you very much for your time. For what it's worth, I already had this freezing thing, though only with `haskell-mode`'s interactive mode, which would only sometimes freeze, but most of the time it would work fine. With `idris2-mode`, I cannot use the REPL at all.

Some more info: I use emacsPgtkNativeComp; and my Doom configuration is at https://bpa.st/UGRA

**Comment by ska80** [comment]
You can disable the `company`‘s completion using the following snippet in your `~/.emacs/init.el`:
```
(setq company-global-modes '(not idris2-mode idris2-repl-mode))```

**Comment by MonAaraj** [comment]
Alright! Thank you so, so very much, it stops the freezes! Though, another issue comes up (though it might be off-topic to this, but I don't think it's quite a bug... but it did act differently for when the REPL above didn't freeze)
When I execute something like `:exec main`, for some reason it uses a different buffer, idris2-process, which takes over the main text file buffer. 

Before running `:exec main`:
![Screenshot_20220601_070813](https://user-images.githubusercontent.com/46468162/171325741-43d36dd0-9b1f-4051-b327-6cd22ee4d84b.png)

After running `:exec main`:
![Screenshot_20220601_070956](https://user-images.githubusercontent.com/46468162/171325802-5388fe83-24f6-4fcd-8bbc-336ef2cf31da.png)

Could I make it show the response *under* the shown prompt? or put the idris2-buffer in a saner place?

**Comment by ska80** [comment]
> Could I make it show the response under the shown prompt?

You need to use the latest Idris from the `main` branch that has a fix for this case.  The output of the running program will still be in the `idris2-process` buffer.

**Comment by MonAaraj** [comment]
Ah, okay. Thank you for your help again, I really appreciate it.
