### ISSUE TITLE
Error when loading file in doom emacs

### ISSUE THREAD

**Issue by olynch** [idris-community/idris2-mode#29]
Whenever I try to load an idris file, I get "error in process filter: Wrong type argument: sequencep, 78".

**Comment by olynch** [comment]
I found the problem. Idris2 0.5.1 is a year old at this point, and the update that makes holes work only got added somewhat recently. So this package only works with unreleased versions of idris2.

**Comment by gallais** [comment]
> the update that makes holes work only got added somewhat recently.the update that makes holes work only got added somewhat recently

It actually got fixed 2 weeks after the release. https://github.com/idris-lang/Idris2/pull/1973
The bug unfortunately snuck into the release and we haven't had one since.
