### ISSUE TITLE
`*idris2-notes*` buffer keeps stealing focus when there's an error if `company-mode` is enabled

### ISSUE THREAD

**Issue by ehamberg** [idris-community/idris2-mode#36]
Whenever I have an error in my code and the `*idris2-notes*` buffer is shown in a window, it steals the focus on key presses such as space, `{`, `}`, `(`, `)`, `,`, `.` and many others, and moves the cursor to the first column of the first line in the `*idris2-notes*` buffer, i.e. on the `-` here:

```
- + Errors (1)
 `-- src/Exercises/Dependent.idr line 75 col 6:
  […]
```

This behaviour makes it almost impossible to actually fix the bug. I'm using Doom Emacs with the latest idris2-mode (3bcb52a65c488f31c99d20f235f6050418a84c9d). Is this a bug, or is something wrong on my end?

**Comment by gallais** [comment]
There's an option you can find using `M-x customize-group RET idris2 RET`:

```
Hide Idris2 Stay In Current Window On Compiler Error: Toggle  on (non-nil)
    State : SAVED and set.
   Stay in current window if type checking fails.
```

I think it may be off by default.

I like my emacs to be minimally noisy so I turned it on (and turned "Hole Show On Load" off)
but I don't know how popular these settings are compared to the defaults.

**Comment by ehamberg** [comment]
@keram:
> can you please try if the same strange behaviour is present when using https://github.com/idris-hackers/idris-mode ?

It is not. The `*idris2-notes*` initially steals the focus, but when I move it back to my file buffer, it stays there, and I can fix the error(s) without the focus jumping back to  `*idris2-notes*`.

> Can you test if the behaviour is present also when other packages are disabled (especially company mode)?

Whoa, if I disable `company-mode` in the buffer, the focus-stealing stops! (The cursor still jumps to the beginning of the line, but that's the only weird behaviour left if I disable `company-mode` and keep  `idris2-stay-in-current-window-on-compiler-error` set to `t`.)

**Comment by gallais** [comment]
It's not the first time `company-mode` seems to interact badly with the `idris2-mode` :weary:

**Comment by ehamberg** [comment]
> It may be worth to add to readme steps to disable it for idris mode buffers. Sounds like interesting issue to figure out but I myself I'm not user of company mode

Yep. This seems to work:

```elisp
(setq company-global-modes '(not idris2-mode))
```

**Comment by jeroendehaas** [comment]
I am seeing the same thing using `corfu`. `*Messages*` notes that:

```elisp
Debugger entered--Lisp error: (error "I can't make sense of the completion task:\n--eval ...")
  error("%s (synchronous Idris2 evaluation failed)" "I can't make sense of the completion task:\n--eval ...")
  funcall(error "%s (synchronous Idris2 evaluation failed)" "I can't make sense of the completion task:\n--eval ...")
  apply(funcall (error "%s (synchronous Idris2 evaluation failed)" "I can't make sense of the completion task:\n--eval ..."))
  idris2-eval((:repl-completions "--eval (LiftIO "))
  idris2-complete-at-point()
```

I feel it might be better to ignore the failed evaluation rather than pass it on. Preparing a PR
