### ISSUE TITLE
Is this repo retired/deprecated?

### ISSUE THREAD

**Issue by sebeaumont** [idris-community/idris2-mode#41]
There seems to be more activity  on idris-hackers/Idris-mode and no updates here for some time.
Suggest this is archived to avoid confusion.

**Comment by sebeaumont** [comment]
No response in three weeks so I guess the answer is yes -- having said that the idris-hackers/idris-mode seems pretty unmaintained also. I guess everyone has jumped ship to vscode or Agda ;-)

**Comment by gallais** [comment]
idris-hackers/idris-mode is only unmaintained in the sense that it works and people use it without needing any new commits to be pushed

**Comment by sebeaumont** [comment]
@gallais Ok so I know which one to fork and use now. I'll PR if I am compelled to fix anything. From what you indicate most of the non-working functionality is therefore Idris 1 legacy.
